export const LOGIN = "LOGIN";
export const LOADING = "LOADING";
//productos
export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const GET_PRODUCTO = "GET_PRODUCTO";
export const GET_PRODUCTO_BY_ID = "GET_PRODUCTO_BY_ID";
export const RESET_PRODUCTO = "RESET_PRODUCTO";
export const GET_PRODS_RANGO_PRECIO = "GET_PRODS_RANGO_PRECIO";
export const ELIMINA_PRODUCTO = "ELIMINA_PRODUCTO";